export const orientation = [
  { path: '/about', nav: 'About', title: 'A place to practise the reasoning.', intro: 'Lighthouse is a practical SOC training environment built around realistic security incidents. Investigate alerts, establish what happened, make defensible decisions, and leave a handover another analyst can act on.', sections: [
    ['Who it is for', 'Start here if you are exploring security operations, preparing for your first analyst role, or want a structured way to practise explaining an investigation. You do not need to operate a live security tool to begin.'],
    ['What makes an investigation useful', 'An alert is a starting point. The work is to establish context, test explanations, decide what action is justified, and document the uncertainty honestly. Lighthouse makes those decisions visible.'],
    ['A practical portfolio project', 'Lighthouse is built by Richard Fisher. Every case is synthetic. Decision scores are self-paced learning feedback, not certification, independent assessment, or a claim of professional SOC experience. The original local incident simulator also models reporter, analyst, and SOC lead workflows.']
  ]},
  { path: '/learn/soc', nav: 'What is a SOC?', title: 'The team behind the alert.', intro: 'A Security Operations Centre (SOC) is a team and operating function that helps an organisation detect, investigate, and respond to security threats. It may work in one room, remotely, or through an external provider.', sections: [
    ['Signals become investigations', 'Security tools collect events from identities, devices, email, applications, and networks. Detections turn some patterns into alerts. Analysts decide which alerts need attention and gather context to understand them.'],
    ['People, process, and tools', 'A SIEM brings security events together for searching and detection. Endpoint tools provide device evidence and authorised response controls. Ticketing and handovers keep work accountable. Tools support a process; they do not make every decision for the team.'],
    ['An everyday example', 'A sign-in appears in two countries within minutes. That could be a stolen account, but it could also be a corporate VPN. A useful investigation correlates the device, session, network, user confirmation, and follow-on activity before deciding what to do.']
  ]},
  { path: '/learn/analyst', nav: 'What does a SOC Analyst do?', title: 'Turn a signal into a defensible next step.', intro: 'SOC analysts assess alerts, investigate context, document findings, and coordinate a proportionate response. Responsibilities vary by organisation, shift, and level of authority.', sections: [
    ['Triage and investigate', 'Identify the affected user or asset, the timing, and the possible impact. Review relevant evidence, establish a timeline, and test both suspicious and legitimate explanations. A quiet log is only useful if you know what it covers.'],
    ['Respond within authority', 'Recommend or carry out actions under an approved procedure. That might mean asking an authorised responder to isolate a device, secure an account, or remove an exposed sharing link. Record whether an action was proposed, attempted, or confirmed successful.'],
    ['Communicate and improve', 'Leave a handover another analyst can continue. Explain false positives carefully, suggest narrowly scoped detection improvements, and escalate questions that require another team. Clear writing is part of the work, not an afterthought.']
  ]},
  { path: '/learn/skills', nav: 'Skills you need', title: 'Build habits as well as technical knowledge.', intro: 'Good investigation combines technical foundations with patient reasoning and clear communication. You do not need to know everything before you start practising.', sections: [
    ['Technical foundations', 'Learn how identities authenticate, how processes run, how email is delivered, and how networks connect. Practise reading timestamps, source addresses, event fields, and authentication outcomes. Understand the limits of each source before drawing a conclusion.'],
    ['Investigation skills', 'Collect relevant evidence, reconstruct a timeline, determine scope, test alternative explanations, and prioritise by impact and confidence. Learn to distinguish potential exposure from confirmed disclosure and blocked activity from a fully prevented incident.'],
    ['Analyst practice', 'Write concise notes. Ask useful questions. Separate facts from assumptions. Preserve evidence, respect response authority, and give the next action an owner. These habits make technical work useful to the rest of the organisation.'],
    ['See your own practice evidence', 'This page explains the profession. Inside the training workspace, Analyst Skills shows individual capabilities, linked cases, and your practice evidence. The library progresses from Introduced to Practised, Demonstrated, and Repeatedly demonstrated.']
  ]},
  { path: '/learn/how-it-works', nav: 'How Lighthouse works', title: 'Learn the reasoning behind the response.', intro: 'Alert → Investigate → Gather Evidence → Decide → Document → Review. Repeat the loop in different situations, then look at which capabilities you can demonstrate across cases.', sections: [
    ['Alert and investigate', 'Read the briefing and the short lesson. Establish the question you are trying to answer rather than jumping straight to a verdict. Each case includes a realistic business context and explicit evidence limits.'],
    ['Gather evidence and decide', 'Inspect the evidence records and cite their IDs in your notebook. Choose three decisions about triage, evidence, and response. The answer key explains why an option is better supported by the supplied facts.'],
    ['Document and review', 'Start with the editable handover template. Write what happened, what remains unknown, what has actually been done, and who owns the next action. Submit, review the feedback, and compare your writing with the example. Notes are self-reviewed; only mapped decisions are automatically scored.'],
    ['Practise again without inflating the evidence', 'A retry replaces the current decision score. Repeated demonstrations require different cases, not repeated clicks on the same answer. Download your record before clearing browser storage or moving to another device.']
  ]}
];
