"use client";
import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, CheckCircle2, ChevronRight, Layers3, Menu, Search, Target, Users, X } from 'lucide-react';
import ProfilePage from './profile';
import Brand from './brand';
import Workspace from './workspace';
import { orientation } from './orientation';
import './public.css';

export default function Site() {
  const [path, setPath] = useState('/');
  const [menu, setMenu] = useState(false);
  useEffect(() => {
    // The server and initial client markup agree; read the browser URL after hydration.
    // oxlint-disable-next-line react/react-compiler
    setPath(window.location.pathname.replace(/\/$/, '') || '/');
  }, []);
  if (path.startsWith('/training')) return <Workspace initialView={path === '/training/skills' ? 'skills' : path === '/training/progress' ? 'progress' : path === '/training/guide' ? 'guide' : 'path'}/>;
  const article = orientation.find(item => item.path === path);
  return <div className="public-site"><a className="skip-link" href="#public-main">Skip to content</a>
    <header className="public-header"><Brand light/><button className="menu-toggle" aria-label={menu ? 'Close navigation' : 'Open navigation'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button><nav className={menu ? 'public-nav is-open' : 'public-nav'} aria-label="Main navigation">{orientation.slice(0,4).map(item => <a aria-current={path === item.path ? 'page' : undefined} key={item.path} href={item.path}>{item.nav}</a>)}</nav><div className="account-actions"><a className="guest-nav" href="/training">Sign in as Guest</a><a className="gold-button" href="/profile">Create Profile</a></div></header>
    <main className="public-main" id="public-main">
      {path === '/' && <>
        <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">PRACTISE THE WORK. UNDERSTAND THE PROFESSION.</p><h1>Learn to investigate.<br/><span>Make the next call<br/>with evidence.</span></h1><p>Lighthouse is a practical SOC training environment built around realistic security incidents. Investigate alerts, establish what happened, make defensible decisions, and leave a handover another analyst can act on.</p><div className="hero-actions"><a className="gold-button hero-cta" href="/training"><strong>Start as a Guest <ArrowRight size={19}/></strong><small>Try a case, no account required</small></a><a className="outline-button hero-cta" href="/profile"><strong>Create Your Profile</strong><small>Track progress on this device</small></a></div><span className="hero-footnote">Six guided cases · Synthetic evidence · Self-paced practice</span></div>
        <div className="product-fragment" aria-label="Example Lighthouse investigation"><div className="fragment-top"><Brand light/><span>LH-102 / IDENTITY</span></div><div className="fragment-heading"><span className="eyebrow">INVESTIGATION LAB</span><h2>Two cities, one session</h2><p>Does the sign-in evidence support account compromise?</p></div><div className="fragment-tabs"><span>01 Briefing</span><strong>02 Evidence</strong><span>03 Decisions</span></div><div className="fragment-evidence"><span>E2 · NETWORK CONTEXT</span><h3>A location change needs an explanation.</h3><dl><div><dt>Observed source</dt><dd>198.51.100.18</dd></div><div><dt>Network context</dt><dd>Approved VPN exit</dd></div><div><dt>Correlated device</dt><dd>HBR-LT-042</dd></div><div><dt>Connection time</dt><dd>02:06 UTC</dd></div></dl></div><div className="fragment-question"><Search size={19}/><p>One clue isn’t a conclusion.<br/><strong>Compare the session, device, and timing.</strong></p></div><a href="/training" className="fragment-link">Open the training workspace <ArrowRight size={16}/></a></div>
        </section>
        <section className="benefit-strip" aria-label="What you can learn">{[[Search,'Hands-on investigations','Realistic guided incidents'],[Target,'Build job-ready skills','Reasoning, tools, evidence and handover'],[Layers3,'Track your progress','Cases, competencies and improvement'],[Users,'Understand the profession','What SOC analysts actually do and why']].map(([Icon,title,copy]) => { const I = Icon as typeof Search; return <div key={String(title)}><I size={25}/><div><h2>{String(title)}</h2><p>{String(copy)}</p></div></div>; })}</section>
        <section className="orientation-section"><div className="section-heading"><div><p className="eyebrow">NEW TO SECURITY OPERATIONS?</p><h2>Understand the work. Then try it.</h2><p>A short orientation to the people, decisions, and capabilities behind an alert.</p></div><a href="/learn/how-it-works">How Lighthouse works <ArrowRight size={17}/></a></div><div className="orientation-grid">{orientation.slice(0,4).map((item,i) => <a className="orientation-card" href={item.path} key={item.path}><span className="case-number">0{i+1}</span><h3>{item.nav === 'About' ? 'About Lighthouse' : item.nav}</h3><p>{['A practical environment for learning to investigate.','Understand the purpose of a Security Operations Centre.','Explore the role from triage to response and handover.','Technical foundations and the habits that make them useful.'][i]}</p><ArrowRight size={20}/></a>)}<a className="orientation-card start-card" href="/training"><CheckCircle2 size={25}/><h3>Start training</h3><p>Work your first alert. Turn the orientation into practice.</p><ArrowRight size={20}/></a></div></section>
        <section className="learning-loop"><div><p className="eyebrow">HOW LIGHTHOUSE WORKS</p><h2>Reasoning you can practise.</h2><p>The goal is a defensible decision and a useful handover.</p><a href="/learn/how-it-works">Explore the learning loop <ArrowRight size={17}/></a></div><ol>{['Alert','Investigate','Gather Evidence','Decide','Document','Review'].map((step,i) => <li key={step}><span>0{i+1}</span>{step}</li>)}</ol></section>
      </>}
      {article && <article className="orientation-article"><a className="text-button" href="/">Lighthouse <ChevronRight size={15}/> Learn</a><p className="eyebrow">{article.nav}</p><h1>{article.title}</h1><p className="article-intro">{article.intro}</p><div className="article-layout"><div>{article.sections.map(([title,body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</div><aside><BookOpen size={26}/><h2>Put it into practice.</h2><p>Read a briefing, inspect the evidence, and make your first analyst decision.</p><a className="primary" href="/training">Start as a Guest <ArrowRight size={17}/></a>{article.path === '/learn/skills' && <a className="text-button" href="/training/skills">Explore Analyst Skills <ArrowRight size={16}/></a>}</aside></div><nav className="orientation-next" aria-label="Orientation pathway">{orientation.map(item => <a key={item.path} aria-current={path === item.path ? 'page' : undefined} href={item.path}>{item.nav}<ChevronRight size={14}/></a>)}</nav></article>}
      {path === '/profile' && <ProfilePage/>}
      {path !== '/' && path !== '/profile' && !article && <section className="orientation-article"><h1>That page isn’t in the casebook.</h1><a className="primary" href="/">Return to Lighthouse</a></section>}
    </main><footer className="public-footer"><Brand/><p>A practical training project by Richard Fisher.<br/>Synthetic cases. Practice feedback, not certification.</p><a href="https://github.com/richfish85/lighthouse-soc" target="_blank" rel="noreferrer">View on GitHub ↗</a><a href="/learn/how-it-works">How Lighthouse works</a></footer>
  </div>;
}
